version: "3.4"
services:
  crowd:
    build:
      context: .
      args:
        - CROWD_VERSION=${CROWD_VERSION}
        - PROXY=${PROXY}
    image: crowd:${CROWD_VERSION}
    restart: always
    stop_grace_period: 5m
    ports:
      - 8002:8095
    volumes:
      - ./volumes/data:/data
      - ./files/atlassian-extras-2.6.jar:/app/crowd/crowd-webapp/WEB-INF/lib/atlassian-extras-3.2.jar
#    mem_limit: 4096m

  postgres:
    image: postgres:11.14-bullseye
    restart: always
    stop_grace_period: 10m
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./files/postgres:/etc/postgresql/conf.d:ro
    environment:
      POSTGRES_PASSWORD: '${PG_PASSWORD}'
      POSTGRES_USER: '${PG_USER}'
      POSTGRES_DB: '${PG_DATABASE}'
      PG_REPLICATION: master
      PG_REPLICA_PASSWORD: '${PG_REPLICA_PASSWORD}'
    ports:
      - 5434:5432
