version: "3.4"
services:

  bitbucket:
    build:
      context: build/bitbucket-server
      dockerfile: Dockerfile
    image: bitbucket:6.4.0
    restart: always
    stop_grace_period: 5m
    ports:
      - ${BITBUCKET_PORT}:7990
      - ${BITBUCKET_PORT_7999}:7999
    depends_on:
      - postgres
    volumes:
      - ./volumes/bitbucket:/data/bitbucket
      - ./volumes/crack/atlassian-extras-decoder-v2-3.3.0.jar:/app/bitbucket/app/WEB-INF/lib/atlassian-extras-decoder-v2-3.3.0.jar:ro
      - ./volumes/crack/atlassian-extras-legacy-3.3.0.jar:/app/bitbucket/app/WEB-INF/lib/atlassian-extras-legacy-3.3.0.jar:ro

  postgres:
    image: postgres:11.14-bullseye
    restart: always
    stop_grace_period: 10m
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
#      - ./files/postgres:/etc/postgresql/conf.d:ro
    environment:
      POSTGRES_PASSWORD: '${PG_PASSWORD}'
      POSTGRES_USER: '${PG_USER}'
      POSTGRES_DB: '${PG_DATABASE}'
#      PG_REPLICATION: master
#      PG_REPLICA_PASSWORD: '${PG_REPLICA_PASSWORD}'
#    ports:
#      - 8090:5432

  bitbucket-backup:
    image: bitbucket-backup-cient:${CLIENT_VERSION:-3.8.0}
    build:
      context: build/bitbucket-backup-client
      dockerfile: Dockerfile
      args:
        VERSION: ${CLIENT_VERSION:-3.8.0}
    environment:
      bitbucket.home: "/source"
      bitbucket.user: ${BB_USER:-admin}
      bitbucket.password: ${BB_PASSWORD:-admin}
      bitbucket.baseUrl: "http://bitbucket:7990"
    volumes:
      - ./volumes/bitbucket:/source:ro
      - ./volumes/backup/bitbucket:/root/bitbucket-backup-client-${CLIENT_VERSION:-3.8.0}/backups
      - /etc/localtime:/etc/localtime:ro
    entrypoint: ["java", "-jar", "/root/bitbucket-backup-client-${CLIENT_VERSION:-3.8.0}/bitbucket-backup-client.jar"]

  bitbucket-restore:
    image: bitbucket-backup-cient:${backup_client_version:-3.8.0}
    build:
      context: build/bitbucket-backup-client
      dockerfile: Dockerfile
      args:
        VERSION: ${CLIENT_VERSION:-3.8.0}
    environment:
      bitbucket.home: "/source"
      #By default, the Restore Client will restore into the same database that was backed up. If jdbc.override is set to true , the Restore Client will restore into the database specified by the jdbc properties in the table below. The database must be empty.
      jdbc.override: true
      jdbc.driver: 'org.postgresql.Driver'
      jdbc.url: "jdbc:postgresql://postgres:5432/${PG_DATABASE}"
      jdbc.user: '${PG_USER}'
      jdbc.password: '${PG_PASSWORD}'
    volumes:
      - ./volumes/bitbucket:/source
      - ./volumes/backup/bitbucket:/root/bitbucket-backup-client-${CLIENT_VERSION:-3.8.0}/backups
      - /etc/localtime:/etc/localtime:ro
    entrypoint: ["java", "-jar", "/root/bitbucket-backup-client-${CLIENT_VERSION:-3.8.0}/bitbucket-restore-client.jar", "/root/bitbucket-backup-client-3.8.0/backups/bitbucket-20220208-095427-186.tar"]
