apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: true
    basicAuthUser: admin
    basicAuthPassword: !r==P=E)5f0IA
    isDefault: true
    editable: true
