version: "3"
services:
  grafana: 
    image: docker.mysite.ir/grafana/grafana:8.2.3 
    ports: 
      - "3000:3000" 
    environment: 
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning 
    volumes: 
      - ./conf/grafana/datasources/default.yaml:/etc/grafana/provisioning/datasources/default.yaml 
      - ./conf/grafana/dashboards/default.yaml:/etc/grafana/provisioning/dashboards/default.yaml 
      - ./conf/grafana/dashboards/sample.json:/var/lib/grafana/dashboards/sample.json
  telegraf:
    image: telegraf:1.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf

  influxdb:
    image: influxdb:1.2
