credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "bitbucket_user"
              username: "admin"
              password: "${JENKINS_BITBUCKET_PASSWORD}"
              description: "Username/Password Credentials for admin of Bitbucket"
          - usernamePassword:
              scope: GLOBAL
              id: "gitlab-hivaa_user"
              username: "root"
              password: "${JENKINS_GITLAB_HIVAA_PASSWORD}"
              description: "Username/Password Credentials for root of Hivaa Gitlab"
          - usernamePassword:
              scope: GLOBAL
              id: "ssh188"
              username: "root"
              password: "${JENKINS_188_PASSWORD}"
              description: "Username/Password Credentials for root of machine IP 188(public)/55(private)"

jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
  authorizationStrategy:
    projectMatrix:
      permissions:
      - "USER:Overall/Administer:admin-crowd"
      - "USER:Overall/Administer:admin"
      - "USER:Overall/Read:hossein_225"
  globalNodeProperties:
  - envVars:
      env:
      - key: ANDROID_SDK_ROOT
        value: /var/lib/jenkins/android-sdk
#      - key: JAVA_OPTS
#        value: '-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'
  securityRealm:
    crowd:
      applicationName: "jenkins"
      group: "jenkins-users"
      password: "${CROWD_JENKINS_PASSWORD}"
      url: "https://crowd.my4030.ir/crowd"

#    local:
#      allowsSignup: false
#      users:
#       - id: admin
#         password: ${ADMIN_PASSWORD:-admin}

#    ldap:
#      configurations:
#        - groupMembershipStrategy:
#            fromUserRecord:
#              attributeName: "memberOf"
#          inhibitInferRootDN: false
#          rootDN: "dc=acme,dc=org"
#          server: "ldaps://ldap.acme.org:1636"

  nodes:
    - permanent:
        name: "static-agent"
        remoteFS: "/home/jenkins"
        launcher:
          jnlp:
            workDirSettings:
              disabled: true
              failIfWorkDirIsMissing: false
              internalDir: "remoting"
              workDirPath: "/tmp"

  slaveAgentPort: 50000
  agentProtocols:
    - "jnlp2"

security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  copyartifact:
    mode: PRODUCTION
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
  sSHD:
    port: -1

jobs:
  - script: >
      job('Job_DSL_Seed') {
        scm {
          git {
            remote {
              url 'https://git.my4030.ir/scm/infra/infra.git'
              credentials('bitbucket_user')
            }
          }
        }
        steps {
          jobDsl {
            targets 'services/jenkins/files/jobs/**/*.groovy'
          }
        }
      }
