jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
  authorizationStrategy:
    projectMatrix:
      permissions:
        - "View/Delete:authenticated"
        - "View/Read:authenticated"
        - "View/Configure:authenticated"
        - "View/Create:authenticated"
        - "Job/Read:authenticated"
        - "Job/Build:authenticated"
        - "Job/Configure:authenticated"
        - "Job/Create:authenticated"
        - "Job/Delete:authenticated"
        - "Job/Discover:authenticated"
        - "Job/Move:authenticated"
        - "Job/Workspace:authenticated"
        - "Job/Cancel:authenticated"
        - "Run/Delete:authenticated"
        - "Run/Replay:authenticated"
        - "Run/Update:authenticated"
        - "SCM/Tag:authenticated"
        - "Overall/Read:anonymous"
        - "Overall/Administer:authenticated"
  globalNodeProperties:
  - envVars:
      env:
      - key: VARIABLE1
        value: foo
      - key: VARIABLE2
        value: bar
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         password: ${ADMIN_PASSWORD:-admin}
#    ldap:
#      configurations:
#        - groupMembershipStrategy:
#            fromUserRecord:
#              attributeName: "memberOf"
#          inhibitInferRootDN: false
#          rootDN: "dc=acme,dc=org"
#          server: "ldaps://ldap.acme.org:1636"

  nodes:
    - permanent:
        name: "static-agent"
        remoteFS: "/home/jenkins"
        launcher:
          jnlp:
            workDirSettings:
              disabled: true
              failIfWorkDirIsMissing: false
              internalDir: "remoting"
              workDirPath: "/tmp"

  slaveAgentPort: 50000
  agentProtocols:
    - "jnlp2"

tool:
  git:
    installations:
      - name: git
        home: /usr/local/bin/git

credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: SYSTEM
              id: ssh_with_passphrase_provided
              username: ssh_root
              passphrase: ${SSH_KEY_PASSWORD}
              description: "SSH passphrase with private key file. Private key provided"
              privateKeySource:
                directEntry:
                  privateKey: ${SSH_PRIVATE_KEY}
      - domain:
          name: "github.com"
          description: "github.com domain"
          specifications:
            - hostnameSpecification:
                includes: "*.github.com"
        credentials:
          - usernamePassword:
              scope: GLOBAL
              id: github_user
              username: admin
              password: "${GITHUB_TOKEN}"
          #- githubAccess:
          #    scope: GLOBAL
          #    id: github_access
          #    username: admin
          #    passphrase: ${GITHUB_TOKEN}
          #    description: "Github access username and password (Token)"

jobs:
  - script: >
      job('Job_DSL_Seed') {
        scm {
          git {
            remote {
              url 'https://github.com/devopsy-ir/devops-tools.git'
            }
          }
        }
        steps {
          jobDsl {
            targets 'jenkins/files/jobs/**/*.groovy'
          }
        }
      }
