version: "3"
services:
  jira:
    #image: jira-software:latest
    build:
      context: .
      args:
        - JIRA_VERSION=${JIRA_VERSION}
        - PROXY=${PROXY}
      dockerfile: ./Dockerfile
    image: docker.my4030.ir/ict/jira:${JIRA_VERSION}
    restart: always
    stop_grace_period: 5m
    ports:
      - ${JIRA_PORT}:8080
    volumes:
      - jira-data:/data/jira
      - jira-conf:/app/jira/conf
#    mem_limit: 8192m
  postgres:
    image: docker.my4030.ir/postgres:11
    restart: always
    stop_grace_period: 10m
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./files/postgres:/etc/postgresql/conf.d:ro
    environment:
      POSTGRES_PASSWORD: '${PG_PASSWORD}'
      POSTGRES_USER: '${PG_USER}'
      POSTGRES_DB: '${PG_DATABASE}'
      #PG_REPLICATION: master
      #PG_REPLICA_PASSWORD: '${PG_REPLICA_PASSWORD}'
    ports:
      - ${PG_PORT}:5432

volumes:
  jira-conf:
    driver: local
    driver_opts:
      o: bind
      type: mount
      device: $PWD/volumes/jira/conf
  jira-data:
    driver: local
    driver_opts:
      o: bind
      type: mount
      device: $PWD/volumes/jira/data
