global:
  scrape_interval: 10s
  evaluation_interval: 10s
rule_files:
  - rules.yml
alerting:
  alertmanagers:
  - static_configs:
    - targets:
        - localhost:9093
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  - job_name: node-188
    static_configs:
      - targets:
          - 172.20.169.55:9100
  - job_name: cadvisor-188
    static_configs:
      - targets:
          - 172.20.169.55:8080
  - job_name: node-168
    static_configs:
      - targets:
          - 172.20.169.57:9100
  - job_name: cadvisor-168
    static_configs:
      - targets:
          - 172.20.169.57:8080
